# Generated by Django 2.0.3 on 2018-03-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/img/default.jpeg', upload_to='')),
                ('name', models.CharField(default='Expert name', max_length=64)),
                ('popularity', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('hours_taught', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(default='English Student', max_length=64)),
                ('education', models.CharField(default='Harvard University', max_length=64)),
                ('description_title', models.CharField(default='Your future English tutor', max_length=64)),
                ('description', models.TextField(default='Type your description here')),
                ('hourly_rate', models.PositiveSmallIntegerField(default=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
