# Generated by Django 2.0.3 on 2018-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='description_title',
            field=models.CharField(default='Your future English tutor!', max_length=64),
        ),
        migrations.AlterField(
            model_name='expert',
            name='picture',
            field=models.ImageField(default='default/profile.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='expert',
            name='popularity',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
